### ISSUE TITLE
Missing Code of Conduct 

### ISSUE THREAD

**Issue by aasthakourav20** [MAVRICK-1/EduWeb#1]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md
Kindly assign this task to me under GSSoC'24 and add labels to it .

**Comment by MAVRICK-1** [comment]
@aasthakourav20 is this project in Gssoc?

**Comment by aasthakourav20** [comment]
Yes , available there

**Comment by MAVRICK-1** [comment]
@aasthakourav20 they have recently add , do one thing add the required md file. Take the help from this 
[Repository](https://github.com/MAVRICK-1/e-commerce_website)  , I will mark it level3

**Comment by aasthakourav20** [comment]
Yes sure , Please assign this issue to me

**Comment by aasthakourav20** [comment]
> @aasthakourav20 they have recently add , do one thing add the required md file. Take the help from this [Repository](https://github.com/MAVRICK-1/e-commerce_website) , I will mark it level3

Hey @MAVRICK-1 , Kindly add labels to this issue
