### ISSUE TITLE
Documentation: Enhance Readme 

### ISSUE THREAD

**Issue by aasthakourav20** [MAVRICK-1/EduWeb#12]
What's missing in this repository !!
The README file is the first thing users and contributors see when they visit your repository. It serves several key purposes:

1. Introduction and Overview: It provides a clear and concise introduction to your project, explaining what it does, its purpose, and why it’s valuable.
2. Installation Instructions: It guides users on how to set up and install the project on their local machines, ensuring they can quickly get started.
3. Usage Guidelines: It offers detailed instructions on how to use the project, including examples and common use cases.
4. Contribution Information: It informs potential contributors on how they can contribute to the project, including any guidelines or requirements they should follow.
5. License Information: It specifies the licensing terms under which the project is distributed, ensuring users and contributors understand their rights and obligations.

hey @MAVRICK-1 , Kindly assign this issue to me under GSSoc'24.

**Comment by MAVRICK-1** [comment]
@aasthakourav20  okay go ahead
