### ISSUE TITLE
Update CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by suhanipaliwal** [MAVRICK-1/EduWeb#15]
The CONTRIBUTING.md file seems a bit unorganised currently and it doesn't have clear guidelines for raising issues and pull requests. I would like to organise it in a better way and add the important guidelines regarding contributing.

Could you please assign this issue to me under GSSOC'24.

**Comment by suhanipaliwal** [comment]
You can refer to this 
https://github.com/urstrulynishkarsh/ReactChat/blob/main/CONTRIBUTING.md
I have added this CONTRIBUTING.md file in this repository.

**Comment by MAVRICK-1** [comment]
@suhanipaliwal okay go ahead

**Comment by MAVRICK-1** [comment]
Hello @suhanipaliwal! Your issue #15 has been closed. Thank you for your contribution!
