### ISSUE TITLE
Workflow for auto commenting an issue creation

### ISSUE THREAD

**Issue by Asymtode712** [MAVRICK-1/EduWeb#17]
# Description

This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

# Screenshot

![issue creation](https://github.com/MAVRICK-1/EduWeb/assets/115717746/5d133519-4f07-43cd-adcb-61236c2ea7da)

**Comment by Asymtode712** [comment]
@MAVRICK-1 please assign me this issue under gssoc'24

**Comment by MAVRICK-1** [comment]
@Asymtode712 for the workflow do everything in 1 PR , i will mark it level3

**Comment by Asymtode712** [comment]
@MAVRICK-1 ok

**Comment by Asymtode712** [comment]
@MAVRICK-1 please add the level label
