### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [MAVRICK-1/EduWeb#27]
### Currently, there is an issue template for this repo( when recent PR will be merged #26), but no issue form which will help users in contributing.
- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/MAVRICK-1/EduWeb/assets/73957207/b13017d6-057a-4703-82fc-df371a85e7af)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by MAVRICK-1** [comment]
@TonyStark-47 go ahead
