### ISSUE TITLE
Icon in footer hide content of that footer

### ISSUE THREAD

**Issue by kapilG0** [MAVRICK-1/EduWeb#33]
![Screenshot_20240522_120448](https://github.com/MAVRICK-1/EduWeb/assets/59639410/721ec882-866d-4341-a518-5ca197b17ed1)

**Comment by kapilG0** [comment]
Hello @MAVRICK-1 please assign this issue to me under gssoc 24

**Comment by MAVRICK-1** [comment]
@kapilG0 go ahead

**Comment by kapilG0** [comment]
Hello @MAVRICK-1 i raised pr https://github.com/MAVRICK-1/EduWeb/pull/38. please check

**Comment by MAVRICK-1** [comment]
closed by #38

**Comment by MAVRICK-1** [comment]
Hello @kapilG0! Your issue #33 has been closed. Thank you for your contribution!
