### ISSUE TITLE
[Feature Request]: Adding a contact/enquiry form 

### ISSUE THREAD

**Issue by masterboy376** [MAVRICK-1/EduWeb#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Whenever we currently click contact button in nav bar we go back to top. I would suggest adding a contact form just above footer using which users can send their inquiries.

### Use Case

Contact button in the navbar will work as expected and users can send their inquiries.

### Benefits

It would be nice UX addition. Users will feel more comfortable to inquire about the services, etc.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by masterboy376** [comment]
Hello @MAVRICK-1 , I would like to work on this issue under gssoc24. I have prior experience of implementing such feature.

**Comment by MAVRICK-1** [comment]
@masterboy376 okay go-ahead , i will add the level after seeing your PR

**Comment by MAVRICK-1** [comment]
Hello @masterboy376! Your issue #34 has been closed. Thank you for your contribution!
