### ISSUE TITLE
[Bug]: Year needs to update dynamic in footer 

### ISSUE THREAD

**Issue by kapilG0** [MAVRICK-1/EduWeb#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in footer static year has passed it should update dynamic 
![image](https://github.com/MAVRICK-1/EduWeb/assets/59639410/fefc3322-a553-4ec9-8157-44b32440c8e0)

### Expected behavior

as mentioned year should update dynamic

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by kapilG0** [comment]
Hello @MAVRICK-1 . please assigned this issue to me under gssoc 24

**Comment by MAVRICK-1** [comment]
@kapilG0 okay go ahead

**Comment by kapilG0** [comment]
> @kapilG0 okay go ahead

please assign this issue to me under gssoc 24 @MAVRICK-1 . thank you

**Comment by kapilG0** [comment]
Hello @MAVRICK-1 i have raised pr https://github.com/MAVRICK-1/EduWeb/pull/40 for this issue. please check.

**Comment by MAVRICK-1** [comment]
Hello @kapilG0! Your issue #39 has been closed. Thank you for your contribution!
