### ISSUE TITLE
[Feature Request]: Login Page

### ISSUE THREAD

**Issue by Ojas-Arora** [MAVRICK-1/EduWeb#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When clicking on Try for Free button nothing happens so I want to make a login page for the same.Kindly assign me this issue @M

### Use Case

Enchancing Interface.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by MAVRICK-1** [comment]
@Ojas-Arora okay go-ahead

**Comment by MAVRICK-1** [comment]
Hello @Ojas-Arora! Your issue #41 has been closed. Thank you for your contribution!
