### ISSUE TITLE
[Documentation Update]: Chatbot option is not available

### ISSUE THREAD

**Issue by ayushkrrana** [MAVRICK-1/EduWeb#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

There is no option of chatbot in the entire website 
Please assign it to me
@ma

### Suggested Change

We can add a scrollable chatbot button on the right hand side

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by ayushkrrana** [comment]
please assign it to me @MAVRICK-1 
Thank you

**Comment by MAVRICK-1** [comment]
@ayushkrrana  required

**Comment by MAVRICK-1** [comment]
Hello @ayushkrrana! Your issue #42 has been closed. Thank you for your contribution!
