### ISSUE TITLE
[Bug]: In the courses the course can be only active if we click on the text not on the whole section

### ISSUE THREAD

**Issue by ayushkrrana** [MAVRICK-1/EduWeb#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![courr](https://github.com/MAVRICK-1/EduWeb/assets/160728166/90880abd-50b0-4b3c-a628-712263f7730d)

In this the course can only clicked by moving the cursor to the text , not on the whole section

### Expected behavior

we have to the pick a course to get started area 
@MAVRICK-1 please assign it to me 
Thank you

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by MAVRICK-1** [comment]
@ayushkrrana OKAY GO AHEAD

**Comment by ayushkrrana** [comment]
@MAVRICK-1 Can you please assign me to level 2 please , i urgently need some points because my Endsem is near
I Did two things :
1)Make whole clickable section of "Pick A Course To Get Started"
2)Make whole clicable section of "Get News With Eduweb"
Thank you, please consider my request

**Comment by MAVRICK-1** [comment]
sry can't do that

**Comment by ayushkrrana** [comment]
@MAVRICK-1 I did two things

**Comment by MAVRICK-1** [comment]
Hello @ayushkrrana! Your issue #43 has been closed. Thank you for your contribution!
