### ISSUE TITLE
[Feature Request]:  ChatBot

### ISSUE THREAD

**Issue by CodeXsubham** [MAVRICK-1/EduWeb#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a chatbot to a website can significantly enhance user engagement, improve customer service, and streamline various interactions. It enhances the website’s functionality, appeal, and effectiveness, ultimately contributing to the overall success of the project.

### Use Case

- Enhanced User Engagement and Satisfaction
- Increased Efficiency and Productivity
- 24/7 Service

Integrating a feature-rich chatbot into a website project can transform user interaction, drive higher engagement and satisfaction, increase operational efficiency, and provide valuable insights for continuous improvement. It enhances the website’s functionality, appeal, and effectiveness, ultimately contributing to the overall success of the project.

### Benefits

- 24/7 Availability
- Live Chat Handoff
- Interactive Elements
- Predefined Responses and FAQs

### Add ScreenShots

![image](https://github.com/MAVRICK-1/EduWeb/assets/119094596/ab7b5130-b09a-4fc7-ab05-cfd6d5500cc3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by CodeXsubham** [comment]
@MAVRICK-1 Hey PA ,
Kindly Look after issue and assign me on this issue , I would like to work on this issue , ThankYou

**Comment by MAVRICK-1** [comment]
@CodeXsubham not needed

**Comment by MAVRICK-1** [comment]
Hello @CodeXsubham! Your issue #48 has been closed. Thank you for your contribution!
