### ISSUE TITLE
[Feature Request]: i want to add location, email and contact icon 

### ISSUE THREAD

**Issue by mukund-gpt** [MAVRICK-1/EduWeb#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

**it helps in better ui**

### Add ScreenShots

![Screenshot 2024-06-02 001021](https://github.com/MAVRICK-1/EduWeb/assets/142800930/d4e00868-c3e1-45d1-a5b9-94e08ce0d4e6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by mukund-gpt** [comment]
**plz, assign the issue to me**

**Comment by MAVRICK-1** [comment]
@mukund-gpt okay go ahead

**Comment by MAVRICK-1** [comment]
Hello @mukund-gpt! Your issue #49 has been closed. Thank you for your contribution!
