### ISSUE TITLE
[Feat] Contact Page

### ISSUE THREAD

**Issue by SaurabhS55** [MAVRICK-1/EduWeb#5]
Hey @MAVRICK-1 , I am saurabh salunke, I am skilled in MERN stack and worked on very good projects. I appreciate your efforts that you put on developing this site. Now, I would like to contribute **Contact page** of this website.

In Contact page I will implement foolowing aspects:

1. Contact form with react form validation.
2. Handling API requests.
3. Storing data to DB
4. sending response email to contact user.

Could you assign this issue to me under GSSOC'24 label?

**Comment by MAVRICK-1** [comment]
@SaurabhS55 thanks for your suggest , but wanna keep it like this.
