### ISSUE TITLE
[Feature Request]: add this type of hover in buttons

### ISSUE THREAD

**Issue by mukund-gpt** [MAVRICK-1/EduWeb#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**i want to add this type of hover in buttons**

### Use Case

**Adding hover on buttons make ui better**

### Add ScreenShots

https://github.com/MAVRICK-1/EduWeb/assets/142800930/208d03f4-03ac-43f3-a05f-224c16934385

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by mukund-gpt** [comment]
**plz, assign the issue to me**

**Comment by MAVRICK-1** [comment]
@mukund-gpt okay go ahead

**Comment by mukund-gpt** [comment]
@MAVRICK-1 Could you please assign the label  **level1**

**Comment by MAVRICK-1** [comment]
Hello @mukund-gpt! Your issue #50 has been closed. Thank you for your contribution!
