### ISSUE TITLE
[Bug]: issue in Find Courses Button

### ISSUE THREAD

**Issue by mukund-gpt** [MAVRICK-1/EduWeb#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**issue in Find Courses Button**

### Expected behavior

**it should jump to the courses section** 

### Add ScreenShots

https://github.com/MAVRICK-1/EduWeb/assets/142800930/a12e69cd-ce84-46e3-ac5f-81249b112f3e

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by mukund-gpt** [comment]
plz, assign the issue to me

**Comment by MAVRICK-1** [comment]
@mukund-gpt what will you plan to do ?

**Comment by MAVRICK-1** [comment]
Hello @mukund-gpt! Your issue #51 has been closed. Thank you for your contribution!
