### ISSUE TITLE
[Bug] : UX : Contact button on navbar leads to Hero section

### ISSUE THREAD

**Issue by SaranshBangar** [MAVRICK-1/EduWeb#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The contact button on navbar leads to Hero section

### Expected behavior

The button should lead to the Contact section (or the footer)

### Add ScreenShots

![image](https://github.com/MAVRICK-1/EduWeb/assets/114401238/bbf2bc64-2433-4941-b8e4-acc93bbe0b03)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by SaranshBangar** [comment]
Resolved in PR #58

**Comment by MAVRICK-1** [comment]
Hello @SaranshBangar! Your issue #56 has been closed. Thank you for your contribution!
