### ISSUE TITLE
[Feature Request] : UI : Addition of custom scroll bar

### ISSUE THREAD

**Issue by SaranshBangar** [MAVRICK-1/EduWeb#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of a custom scroll bar makes the website look more professional

### Use Case

Addition of custom scroll bar has resulted in higher viewer retention in multiple websites

### Benefits

It would make the website look more professional and clean

### Add ScreenShots

![Screenshot 2024-06-03 185420](https://github.com/MAVRICK-1/EduWeb/assets/114401238/0df99be1-bd3d-4c25-a117-9ef918b7711c)

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by MAVRICK-1** [comment]
@SaranshBangar not needed

**Comment by MAVRICK-1** [comment]
Hello @SaranshBangar! Your issue #57 has been closed. Thank you for your contribution!
