### ISSUE TITLE
[Feature Request]: Want to add hover effect on social media links

### ISSUE THREAD

**Issue by mukund-gpt** [MAVRICK-1/EduWeb#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Use Case

https://github.com/MAVRICK-1/EduWeb/assets/142800930/92f22954-64da-4856-95fe-ec03f2254784

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by MAVRICK-1** [comment]
@mukund-gpt go-ahead

**Comment by MAVRICK-1** [comment]
Hello @mukund-gpt! Your issue #61 has been closed. Thank you for your contribution!
