### ISSUE TITLE
[Feature Request]:  Wanted to Create a contact Us form

### ISSUE THREAD

**Issue by mukund-gpt** [MAVRICK-1/EduWeb#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Wanted to Create a contact Us form which will directly send messages to gmail through**
### web3forms
https://web3forms.com/

### Use Case

![Screenshot 2024-06-04 010949](https://github.com/MAVRICK-1/EduWeb/assets/142800930/efd03df0-80a2-41b8-b633-c0e54b66e2e0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by mukund-gpt** [comment]
### Contact us form will also be responsive in mobile view
![image](https://github.com/MAVRICK-1/EduWeb/assets/142800930/2e1b936f-f832-489f-9089-6999388c6a74)

**plz assign the issue**

**Comment by MAVRICK-1** [comment]
@mukund-gpt already created

**Comment by MAVRICK-1** [comment]
Hello @mukund-gpt! Your issue #62 has been closed. Thank you for your contribution!
