### ISSUE TITLE
Adding contributors image list 

### ISSUE THREAD

**Issue by Arpcoder** [MAVRICK-1/EduWeb#7]
![Screenshot 2024-05-18 124533](https://github.com/MAVRICK-1/EduWeb/assets/100352419/126991e6-f96e-46f3-bdb4-291104f0e1f4)

**Comment by MAVRICK-1** [comment]
@Arpcoder okay go ahead and change readme file also

**Comment by Arpcoder** [comment]
> @Arpcoder okay go ahead and change readme file also

Thank you.Please add level label as well.

**Comment by MAVRICK-1** [comment]
@Arpcoder i will give the level after seeing your pr

**Comment by Arpcoder** [comment]
> @Arpcoder i will give the level after seeing your pr

🥲

**Comment by Arpcoder** [comment]
@MAVRICK-1 Please add  level1 labels to this issue as well, else my score for this won't be counted. Thank you

**Comment by Arpcoder** [comment]
> @MAVRICK-1 Please add level1 labels to this issue as well, else my score for this won't be counted. Thank you

@MAVRICK-1 Please consider this

**Comment by MAVRICK-1** [comment]
@Arpcoder levels on issues don't count z levels on PR counts
