### ISSUE TITLE
Adding the content in about us in this website

### ISSUE THREAD

**Issue by Its-your-rj** [MAVRICK-1/EduWeb#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

<img width="648" alt="Screenshot 2024-06-10 094203" src="https://github.com/MAVRICK-1/EduWeb/assets/131703345/8343e139-b8d3-43e6-842f-836b80f3a2db">

It is important to add proper content under the about us section so that user can easily trust on this platform by reading about us section. Please assign me this task under GSSOC'24 with tags of level 3 It will really help me a lot.
Thanking you
Raj Mehta

### Use Case

- improves user experience
- build trust among user

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by Its-your-rj** [comment]
@MAVRICK-1  we can add the following content:
Welcome to Eduweb!
At Eduweb, we are committed to enabling people via online education and skill-building. We have spearheaded the educational revolution, enabling everyone, wherever, to access top-notch education, with more than ten years of experience in the sector.

Our mission
Our goal is to close the gap that exists between accessibility and education. In our opinion, there should be no restrictions on learning related to time, place, or money. Our mission is to offer comprehensive, cost-effective, and adaptable learning solutions that meet the various demands of our international community.

our Vision
We see a society in which everyone, regardless of circumstances or background, has the chance to learn and develop. We hope to foster a culture of lifelong learning and continual growth through our cutting-edge platform, giving people the tools they need to thrive in a world that is changing all the time.

What We Provide
Diverse Courses: Our vast catalog includes options for everyone, from technical skills and professional credentials to creative arts and personal growth. Experts in the field create each course, which is then presented through dynamic, interesting content.

Flexible Learning: We understand that life is busy. Because of the way our courses are made to fit into your schedule, you can learn at your own speed, whenever and whenever you choose.

Professional Teachers: Gain knowledge from the industry leaders. Our professors are accomplished experts with a plethora of real-world expertise. They pledge to mentor you during your educational path, offering encouragement and constructive criticism at each stage.

Community Support: You're never alone at Eduweb. Become a part of a lively global learning community. Ask questions, discuss ideas, and work together on projects. Our discussion boards and forums are the ideal setting for networking and mutual development.

Accreditation and Recognition: After finishing the course, get certificates attesting to your acquired knowledge and abilities. Employers and organizations respect our certifications, which provides you with the professional advantage you need.

Our  Journey
The goal of democratizing education was the driving force behind the founding of Eduweb more than a decade ago. Since then, we have developed into a reputable platform that helps thousands of students worldwide. Our dedication to excellence in teaching and innovation has brought us many honors and a devoted student body.

Join Us
Eduweb is here to help you at every stage, whether your goal is to grow in your profession, take up a new interest, or just learn more. Accompany us on this fascinating educational and exploratory voyage. Let's work together to realize your potential and create a more promising future.

Eduweb – Learning Without Limits.

We can add the above content in this website as it 1) builds trust and credibility 2) personal connection to clients 3)Customer Reassurance etc 

please assign me this task under GSSOC'24 along with the labels of level 4 and gssoc. It would be a great help to me.

Thanking you 
Raj Mehta

**Comment by MAVRICK-1** [comment]
@Its-your-rj go ahead, will mark you level after seeing your pr

**Comment by MAVRICK-1** [comment]
Hello @Its-your-rj! Your issue #73 has been closed. Thank you for your contribution!

**Comment by Its-your-rj** [comment]
@MAVRICK-1 Thanks ♥️
