### ISSUE TITLE
[Feature Request]: Adding Hover Effect on "Categories" Grid-List

### ISSUE THREAD

**Issue by codestorm31** [MAVRICK-1/EduWeb#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The UI of the Homepage can be improved by adding Hover effect on "Categories" Grid-List. 

I wish to add hover effect transition on the elements of the gird list to enhance User Interface and Experience.
@MAVRICK-1  Kindly assign me this issue along with GSSOC & Level labels please.

### Use Case

When user hovers the cursor on the grid-list elements they should feel interactive as it adds to the overall User-Experience.
Adding the hover feature would thus improve UI.

### Add ScreenShots

Currently the grid-list lacks any hover effect.
![Screenshot 2024-06-11 132224](https://github.com/MAVRICK-1/EduWeb/assets/96651367/af3264ae-c6cc-449f-a37a-fd52683cbdb0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by MAVRICK-1** [comment]
@codestorm31 go ahead

**Comment by MAVRICK-1** [comment]
Hello @codestorm31! Your issue #78 has been closed. Thank you for your contribution!
