### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by sanskriti-lal** [MAVRICK-1/EduWeb#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="424" alt="Screenshot 2024-06-12 at 3 43 39 PM" src="https://github.com/MAVRICK-1/EduWeb/assets/165655543/1dde0916-9ef4-4e5b-a69c-3bd44afa3da4">

### Expected behavior

Instead of contacts , contact should be there.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by MAVRICK-1** [comment]
Hello @sanskriti-lal! Your issue #80 has been closed. Thank you for your contribution!
