### ISSUE TITLE
Feature 🌟: Add "Terms and Conditions" and "Privacy Policy" Pages to Footer

### ISSUE THREAD

**Issue by aslams2020** [MAVRICK-1/EduWeb#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MAVRICK-1,
I would like to contribute to this project by addressing an issue in the footer of the website. 

In the "Links" section of the footer, there are currently **no links** for **"Terms and Conditions"** and **"Privacy Policy."** 
These are essential pages for any website to ensure users are aware of the terms and privacy policies they are agreeing to by using the site.

I would **like to add these pages** in the footer section with their Respective Pages -

![image](https://github.com/MAVRICK-1/EduWeb/assets/131389695/1240f147-e23b-4e78-af36-522116bf7bc5)

### Use Case

- A user visits the website and wants to understand the terms they are agreeing to by using the site as well as how their data is being handled.
- The user scrolls down to the footer looking for "Terms and Conditions" and "Privacy Policy" links.
- Currently, the user cannot find these links, leading to a lack of transparency and potential trust issues. By adding these links, the user can easily access the necessary information, leading to a more trustworthy and transparent user experience.

### Benefits

Enhanced User Experience, Compliance and trust and transparency

Could you please assign me this issue under GSSOC'24?

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md) for guidelines on contributing to this project.

**Comment by masterboy376** [comment]
Hello @MAVRICK-1 I would like to work on this issue under gssoc'24.

**Comment by aslams2020** [comment]
@MAVRICK-1
